#
# Example ddocker Dockerfile template to build a docker image with
# ddocker installed into /opt/ddocker.
#

REGISTRY my.registry:80
REPOSITORY testing/foobar

FROM ubuntu:12.04
MAINTAINER Tom Arnfeld <tom@duedil.com>

WORKDIR /opt/ddocker
ADD ../ /opt/ddocker
