# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ddocker.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ddocker.proto',
  package='ddocker',
  serialized_pb='\n\x13proto/ddocker.proto\x12\x07\x64\x64ocker\"!\n\nCheckpoint\x12\x13\n\x0b\x66rameworkId\x18\x01 \x02(\t\"v\n\x0b\x44ockerImage\x12+\n\tnamespace\x18\x01 \x02(\x0b\x32\x18.ddocker.DockerNamespace\x12-\n\nrepository\x18\x02 \x02(\x0b\x32\x19.ddocker.DockerRepository\x12\x0b\n\x03tag\x18\x03 \x03(\t\"\x1f\n\x0f\x44ockerNamespace\x12\x0c\n\x04name\x18\x01 \x02(\t\" \n\x10\x44ockerRepository\x12\x0c\n\x04name\x18\x01 \x02(\t\"0\n\x0e\x44ockerRegistry\x12\x10\n\x08hostname\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\r')




_CHECKPOINT = _descriptor.Descriptor(
  name='Checkpoint',
  full_name='ddocker.Checkpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameworkId', full_name='ddocker.Checkpoint.frameworkId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=65,
)


_DOCKERIMAGE = _descriptor.Descriptor(
  name='DockerImage',
  full_name='ddocker.DockerImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ddocker.DockerImage.namespace', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repository', full_name='ddocker.DockerImage.repository', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='ddocker.DockerImage.tag', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=185,
)


_DOCKERNAMESPACE = _descriptor.Descriptor(
  name='DockerNamespace',
  full_name='ddocker.DockerNamespace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ddocker.DockerNamespace.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=218,
)


_DOCKERREPOSITORY = _descriptor.Descriptor(
  name='DockerRepository',
  full_name='ddocker.DockerRepository',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ddocker.DockerRepository.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=252,
)


_DOCKERREGISTRY = _descriptor.Descriptor(
  name='DockerRegistry',
  full_name='ddocker.DockerRegistry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='ddocker.DockerRegistry.hostname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='ddocker.DockerRegistry.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=254,
  serialized_end=302,
)

_DOCKERIMAGE.fields_by_name['namespace'].message_type = _DOCKERNAMESPACE
_DOCKERIMAGE.fields_by_name['repository'].message_type = _DOCKERREPOSITORY
DESCRIPTOR.message_types_by_name['Checkpoint'] = _CHECKPOINT
DESCRIPTOR.message_types_by_name['DockerImage'] = _DOCKERIMAGE
DESCRIPTOR.message_types_by_name['DockerNamespace'] = _DOCKERNAMESPACE
DESCRIPTOR.message_types_by_name['DockerRepository'] = _DOCKERREPOSITORY
DESCRIPTOR.message_types_by_name['DockerRegistry'] = _DOCKERREGISTRY

class Checkpoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKPOINT

  # @@protoc_insertion_point(class_scope:ddocker.Checkpoint)

class DockerImage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCKERIMAGE

  # @@protoc_insertion_point(class_scope:ddocker.DockerImage)

class DockerNamespace(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCKERNAMESPACE

  # @@protoc_insertion_point(class_scope:ddocker.DockerNamespace)

class DockerRepository(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCKERREPOSITORY

  # @@protoc_insertion_point(class_scope:ddocker.DockerRepository)

class DockerRegistry(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCKERREGISTRY

  # @@protoc_insertion_point(class_scope:ddocker.DockerRegistry)


# @@protoc_insertion_point(module_scope)
